### ISSUE TITLE
badges broken in readme :-(

### ISSUE THREAD

**Issue by nelsonic** [dwyl/aguid#10]
see: https://www.npmjs.com/package/aguid
![aguid-badges-broken](https://cloud.githubusercontent.com/assets/194400/20270532/5618f598-aa7f-11e6-85aa-df17d3ea270b.png)

**Comment by sohilpandya** [comment]
It was a strange issue, for some reason the Codecov got out of sync with the repo, Just re-ran an existing build on [travis](https://travis-ci.org/dwyl/aguid) and the coverage is all ok now. 🎉 
![screen shot 2016-11-16 at 22 26 31](https://cloud.githubusercontent.com/assets/2305591/20368394/c1b51796-ac4b-11e6-8bb5-9da2c5d83fa9.png)

**Comment by nelsonic** [comment]
@sohilpandya thanks! ❤️  ✅
