### ISSUE TITLE
Request: Update to uuid module

### ISSUE THREAD

**Issue by goncaloneves** [dwyl/aguid#11]
Hi @nelsonic,

Thanks for this amazing little module 👍 

Can you guys update from legacy node-uuid to uuid?

It will be helpful to keep to the most current version.

**Comment by nelsonic** [comment]
@goncaloneves Tudo Bom? 😉 
Thanks for getting in touch and _suggesting_ we update the dependency to use `uuid`.
Totally agree that we need to update. (_requirement validated_) ✅ 

If you have time, please create a Pull Request and I will review/approve/merge and publish a new version to NPM once all CI checks pass...

You've been invited to join DWYL: https://github.com/dwyl 
and you now have **_write_ access** to the Repo. (_great power/responsibility, yada yada..._)

Please follow create a Pull Request following these steps:
[dwyl/contributing#step-3-prepare-a-pull-request-pr-and-assign-to-someone-else-for-review](https://github.com/dwyl/contributing/tree/4f38e20b95eb6d3a950e6f8f9f44bbd977ae87d8#step-3-prepare-a-pull-request-pr-and-assign-to-someone-else-for-review)

We can get `this` done _today_ if you have time. ⏳ 
please/thanks! 🎉

**Comment by goncaloneves** [comment]
Oi Nelson! 😄 

Alright, I will be doing this.

Thanks! 🏊
